instances	CREATE TABLE `instances` (
  `Identity` varchar(100) NOT NULL,
  `Description` text,
  `ServerHostname` varchar(100) DEFAULT NULL,
  `ServerUrl` text,
  `ServerIp` varchar(50) DEFAULT NULL,
  `ServerPort` int DEFAULT '28015',
  `RconIp` varchar(50) DEFAULT NULL,
  `RconPort` int DEFAULT '28016',
  `AppPort` int NOT NULL DEFAULT '0',
  `RconPassword` text,
  `RconWeb` int DEFAULT '0',
  `MaxPlayers` int DEFAULT NULL,
  `ServerTickrate` int DEFAULT '1',
  `ServerSaveInterval` int DEFAULT '300',
  `UseCustomMap` tinyint(1) DEFAULT '0',
  `Seed` int DEFAULT NULL,
  `WorldSize` int DEFAULT NULL,
  `Level` varchar(255) DEFAULT NULL,
  `MapName` varchar(100) DEFAULT NULL,
  `ServerLevelUrl` text,
  `SteamCmdPath` text,
  `InstallDirectory` text,
  `RustDedicatedProcess` text,
  `ServerCfg` text,
  `MySqlHost` varchar(100) DEFAULT NULL,
  `MySqlPort` int DEFAULT NULL,
  `MySqlUsername` varchar(100) DEFAULT NULL,
  `MySqlPassword` text,
  `MySqlDatabaseName` varchar(100) DEFAULT NULL,
  `AutoStart` tinyint(1) DEFAULT '0',
  `AutoUpdate` tinyint(1) DEFAULT '0',
  `LastWiped` date DEFAULT NULL,
  `ProcessId` int DEFAULT NULL,
  `EnableGracefulShutdown` tinyint(1) DEFAULT '0',
  `ShutdownDelaySeconds` int DEFAULT '30',
  `ShutdownMessageCommand` varchar(255) DEFAULT 'say Server shutting down in {seconds} seconds',
  PRIMARY KEY (`Identity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
